// MOVIES
export const FETCH_ALL_MOVIES = 'FETCH_ALL_MOVIES'
export const FETCH_DETAIL_MOVIES = 'FETCH_DETAIL_MOVIES'
export const POST_MOIVIES = 'POST_MOIVIES'
export const DELETE_MOVIES = 'DELETE_MOVIES'